# Generated by Django 6.0.6 on 2026-06-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherence',
            fields=[
                ('adherenceID', models.AutoField(primary_key=True, serialize=False)),
                ('adherenceStatus', models.CharField(max_length=20)),
                ('recordedTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('passwordHash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('caregiverID', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('passwordHash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medicationID', models.AutoField(primary_key=True, serialize=False)),
                ('medicationName', models.CharField(max_length=100)),
                ('colorBoxCode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('phoneNumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alertID', models.AutoField(primary_key=True, serialize=False)),
                ('alertType', models.CharField(max_length=30)),
                ('alertTime', models.DateTimeField()),
                ('alertStatus', models.CharField(max_length=20)),
                ('adherenceID', models.ForeignKey(db_column='adherenceID', on_delete=django.db.models.deletion.CASCADE, to='caregiverApp.adherence')),
                ('caregiverID', models.ForeignKey(db_column='caregiverID', on_delete=django.db.models.deletion.CASCADE, to='caregiverApp.caregiver')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCaregiver',
            fields=[
                ('patientCaregiverID', models.AutoField(primary_key=True, serialize=False)),
                ('assignmentStatus', models.CharField(max_length=20)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('caregiverID', models.ForeignKey(db_column='caregiverID', on_delete=django.db.models.deletion.CASCADE, to='caregiverApp.caregiver')),
                ('patientID', models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='caregiverApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescriptionID', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('medicationID', models.ForeignKey(db_column='medicationID', on_delete=django.db.models.deletion.CASCADE, to='caregiverApp.medication')),
                ('patientID', models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='caregiverApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionSchedule',
            fields=[
                ('scheduleID', models.AutoField(primary_key=True, serialize=False)),
                ('scheduledTime', models.TimeField()),
                ('frequency', models.CharField(max_length=30)),
                ('prescriptionID', models.ForeignKey(db_column='prescriptionID', on_delete=django.db.models.deletion.CASCADE, to='caregiverApp.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminderID', models.AutoField(primary_key=True, serialize=False)),
                ('sentTime', models.DateTimeField()),
                ('deliveryStatus', models.CharField(max_length=20)),
                ('scheduleID', models.ForeignKey(db_column='scheduleID', on_delete=django.db.models.deletion.CASCADE, to='caregiverApp.prescriptionschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('responseID', models.AutoField(primary_key=True, serialize=False)),
                ('patientReply', models.CharField(max_length=10)),
                ('responseTime', models.DateTimeField()),
                ('reminderID', models.ForeignKey(db_column='reminderID', on_delete=django.db.models.deletion.CASCADE, to='caregiverApp.reminder')),
            ],
        ),
        migrations.AddField(
            model_name='adherence',
            name='responseID',
            field=models.ForeignKey(db_column='responseID', on_delete=django.db.models.deletion.CASCADE, to='caregiverApp.response'),
        ),
    ]
