# Generated by Django 6.0.6 on 2026-06-21 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiverApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionschedule',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='prescriptionschedule',
            name='prescriptionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='caregiverApp.prescription'),
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('logID', models.AutoField(primary_key=True, serialize=False)),
                ('logDate', models.DateField(auto_now_add=True)),
                ('medStatus', models.CharField(default='Pending', max_length=20)),
                ('takenAt', models.DateTimeField(blank=True, null=True)),
                ('scheduleID', models.ForeignKey(db_column='daily_logs', on_delete=django.db.models.deletion.CASCADE, to='caregiverApp.prescriptionschedule')),
            ],
        ),
    ]
