# Generated by Django 6.0.6 on 2026-06-22 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiverApp', '0002_remove_prescriptionschedule_frequency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='caregiverID',
            field=models.ForeignKey(db_column='caregiverID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
