# Generated by Django 6.0.6 on 2026-06-24 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiverApp', '0003_patient_caregiverid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationlog',
            name='scheduleID',
            field=models.ForeignKey(db_column='scheduleID', on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='caregiverApp.prescriptionschedule'),
        ),
    ]
